// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://auyfhtakatrofhwpymkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1eWZodGFrYXRyb2Zod3B5bWtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NTc2MTUsImV4cCI6MjA1ODMzMzYxNX0.5S6HPfbi0bpEjRUyH2_4OXAouFGoWfBa9yd_szsIfOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);