
// This file is automatically generated. Do not edit it directly.
import { mockApiClient } from '../../api/mockApiClient';

// Export the mock API client as a drop-in replacement for Supabase
export const supabase = mockApiClient;
